
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: tigera-elasticsearch
  namespace: tigera-elasticsearch
provisioner: kubernetes.io/host-path


---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: tigera-elasticsearch-1
  namespace: calico-monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/tigera/elastic-data/1
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: tigera-elasticsearch


